
title: When in Rome
email: annapepechkova9797@gmial.com
destination: docs
description: the first one site 
baseurl: ""
url: ""
twitter_username: apepechkova
github_username: pepechkova
destination: docs


exclude: [_assets, node_modules, Gemfile, Gemfile.lock, gulpfile.js,package.json]

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed

